cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/OR','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/corrMag0/Delay7','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/corrMag0/Delay8','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/corrMag0/Delay9','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/corrMag1/Delay7','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/corrMag1/Delay8','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/corrMag1/Delay9','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/signalMagAverage/Constant1','user1');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/signalMagAverage/Product','user1');
