open_system('nrhdlSignalDetection');
open_system('gm_nrhdlSignalDetection');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 0/pipelinedMax', 'user1');
annotate_port('gm_nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 0/pipelinedMax', 0, 1, 'Delays not moved into or out of a subsystem because DistributedPipelining=off');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 0/pipelinedMax', 'user1');
annotate_port('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 0/pipelinedMax', 0, 1, 'Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 1/pipelinedMax', 'user1');
annotate_port('gm_nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 1/pipelinedMax', 0, 1, 'Delays not moved into or out of a subsystem because DistributedPipelining=off');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 1/pipelinedMax', 'user1');
annotate_port('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 1/pipelinedMax', 0, 1, 'Delays not moved into or out of a subsystem because DistributedPipelining=off');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 2/pipelinedMax', 'user1');
annotate_port('gm_nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 2/pipelinedMax', 0, 1, 'Delays not moved into or out of a subsystem because DistributedPipelining=off');
hilite_system('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 2/pipelinedMax', 'user1');
annotate_port('nrhdlSignalDetection/SSB Detect and Demod/PSS Detector/Find Peak/filter peaks 2/pipelinedMax', 0, 1, 'Delays not moved into or out of a subsystem because DistributedPipelining=off');
